//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasWeb
{
    public partial class Preguntas
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.HyperLink VolverLink;

        protected global::System.Web.UI.WebControls.Literal TituloLiteral;

        protected global::System.Web.UI.WebControls.Literal DescripcionLiteral;

        protected global::System.Web.UI.WebControls.Panel PreguntasPanel;

        protected global::System.Web.UI.WebControls.Panel ErroresPanel;

        protected global::System.Web.UI.WebControls.Literal ErroresLiteral;

        protected global::System.Web.UI.WebControls.Button FinalizarButton;
    }
}
