//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasWeb
{
    public partial class Respuestas
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.HyperLink InicioLink;

        protected global::System.Web.UI.WebControls.Literal TituloLiteral;

        protected global::System.Web.UI.WebControls.Literal MetaLiteral;

        protected global::System.Web.UI.WebControls.Repeater RespuestasRepeater;

        protected global::System.Web.UI.WebControls.Literal MensajeLiteral;

        protected global::System.Web.UI.WebControls.Button ImprimirButton;
    }
}
